# Generated by Django 4.2.20 on 2025-04-22 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('expense_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseSubCategory',
            fields=[
                ('expense_sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_sub_category_name', models.CharField(max_length=100)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_description', models.TextField()),
                ('expense_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateTimeField()),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expensecategory')),
                ('expense_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.expensesubcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
