# Generated by Django 4.2.20 on 2025-04-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user_challenge_id',
            new_name='user_challenge',
        ),
    ]
