# Generated by Django 4.2.20 on 2025-04-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_images/'),
        ),
    ]
