# Generated by Django 4.2.20 on 2025-04-24 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_profile_image',
        ),
    ]
