# Generated by Django 4.2.20 on 2025-05-22 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mileage',
            new_name='point',
        ),
    ]
