# Generated by Django 4.2.20 on 2025-04-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
