# Generated by Django 4.2.20 on 2025-04-25 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_reward_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reward',
            name='valid_days',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewardtransaction',
            name='expire_at',
            field=models.DateTimeField(default='2025-05-25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewardtransaction',
            name='redeemed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
