# Generated by Django 4.2.20 on 2025-04-25 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_reward_description_reward_valid_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewardtransaction',
            old_name='is_changed',
            new_name='status',
        ),
        migrations.CreateModel(
            name='RewardImage',
            fields=[
                ('reward_image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='reward_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rewards.reward')),
            ],
        ),
    ]
