# Generated by Django 4.2.20 on 2025-05-22 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_rename_is_changed_rewardtransaction_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='cost',
            new_name='point',
        ),
    ]
