# Generated by Django 4.2.20 on 2025-05-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_rename_cost_reward_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='category',
            field=models.CharField(default='기타', max_length=50),
        ),
    ]
