# Generated by Django 4.2.20 on 2025-04-22 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challenge_id', models.AutoField(primary_key=True, serialize=False)),
                ('challenge_title', models.CharField(max_length=100)),
                ('challenge_content', models.TextField()),
                ('challenge_target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('challenge_status', models.CharField(max_length=20)),
                ('challenge_start_date', models.DateTimeField()),
                ('challenge_end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('user_challenge_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_challenge_total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user_challenge_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user_challenge_status', models.CharField(max_length=20)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeHost',
            fields=[
                ('challenge_host_id', models.AutoField(primary_key=True, serialize=False)),
                ('challenge_host_company_name', models.TextField()),
                ('challenge_host_phone_number', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenge_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challengehost'),
        ),
    ]
