# Generated by Django 4.2.20 on 2025-05-22 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_user_challenge_id_expense_user_challenge'),
        ('challenges', '0002_alter_challenge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.category'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='reward_mileage',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
