# Generated by Django 4.2.20 on 2025-05-22 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_user_challenge_id_expense_user_challenge'),
        ('challenges', '0003_challenge_category_challenge_reward_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='goal_days',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='expenses.category'),
        ),
    ]
