# Generated by Django 4.2.20 on 2025-05-22 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_challenge_goal_days_alter_challenge_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='reward_mileage',
            new_name='point',
        ),
    ]
