# Generated by Django 4.2.20 on 2025-05-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_userchallenge_end_date_userchallenge_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='goal_amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
