# Generated by Django 4.2.20 on 2025-05-22 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_remove_challenge_status_challenge_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='status',
            field=models.CharField(choices=[('도전중', '도전중'), ('성공', '성공'), ('실패', '실패')], default='도전중', max_length=20),
        ),
    ]
